# Generated by Django 3.2 on 2022-01-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersalary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersalary',
            options={'verbose_name_plural': 'User Salaries'},
        ),
    ]
